- name: Set up SSH key
  uses: webfactory/ssh-agent@v0.5.3
  with:
    ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

- name: Deploy Application
  run: |
    cd /var/www/gci/backseatdriver/src
    git pull origin main
    npm install
    npm run build
    pm2 delete backseatdriver || true
    pm2 serve build 3000 --name "backseatdriver" --spa
